Traceback (most recent call last):
  File "/Users/noorainkazmi/Documents/GitHub/weights-biases/decision_tree_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/Users/noorainkazmi/Documents/GitHub/weights-biases/decision_tree_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'max_sweeps'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/noorainkazmi/Documents/GitHub/weights-biases/iris--model--sweep.py", line 21, in <module>
    max_sweeps = wandb.config.max_sweeps
  File "/Users/noorainkazmi/Documents/GitHub/weights-biases/decision_tree_env/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'max_sweeps'